[project]
name = "llm-rags"
version = "0.1.0"
description = "First version of the installer"
authors = [
    {name = "omidh.usa@gmail.com"}
]
readme = "README.md"
requires-python = ">=3.9"
dependencies = [
]


[tool.poetry.dependencies]
python = ">=3.11.13,<3.12"
numpy = "<2"
httpx = "^0.27"

langchain = "^0.2"
langchain-community = "^0.2"

huggingface-hub = ">=0.34.0,<1.0"
sentence-transformers = "^2.7"
torch = ">=2.0.0,<=2.9.1"


[tool.poetry.scripts]
omid-llm = "omid_llm.main:main"


[build-system]
requires = ["poetry-core>=2.0.0,<3.0.0"]
build-backend = "poetry.core.masonry.api"


