[project]
name = "omid_llm"
version = "0.1.0"
description = "First version of the installer"
authors = [
    {name = "omidh.usa@gmail.com"}
]
readme = "README.md"
requires-python = ">=3.9"
dependencies = [
]


[tool.poetry.dependencies]
python = ">=3.11.13,<3.12"
numpy = "<2"
httpx = "^0.27"

langchain-core = "<0.3.0"
langchain-community = "^0.2.19"
langchain-huggingface = "<1.0.0"

huggingface-hub = ">=0.34.0,<1.0"
sentence-transformers = "^2.7"
torch = ">=2.0.0,<=2.9.1"
torchvision = "^0.17.2"

pyyaml = "^6.0.1"
omegaconf = "^2.3.0"
hydra-core = "^1.3.2"
pandas = "^2.2.1"

ipython = "^8.23.0"
tensorboard = "^2.16.2"

#[tool.poetry.scripts]
#omid-llm = "omid_llm.main:main"


[build-system]
requires = ["poetry-core>=2.0.0,<3.0.0"]
build-backend = "poetry.core.masonry.api"


