experiment_name: "chroma_ingest"
output_dir: ./outputs/${experiment_name}

hydra:
  run:
    dir: ${output_dir}

version: 1.1.0
defaults:
  - _self_

logging:
  file: "run_hydra.log"

data:
  path: "../../datasets/sample_pdfs_rag_database"

database:
  persist_path: "chroma"
  reset: false

text_splitter:
  chunk_size: 800
  chunk_overlap: 80
